/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qvoice_init.h"

/* Header for class com_qdreamer_qvoice_QAudio */
#ifndef _Included_com_qdreamer_qvoice_QAudio
#define _Included_com_qdreamer_qvoice_QAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    init
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_qvoice_QAudio_init
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    exit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_exit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    recorderStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_recorderStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    recorderStop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_recorderStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    recorderRead
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QAudio_recorderRead
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    recorderGetChannel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_recorderGetChannel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    recorderGetRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_recorderGetRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    recorderGetBytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_recorderGetBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerStop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerSetFormat
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerSetFormat
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerPlay
 * Signature: (J[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerPlay
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerInterrupt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerInterrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerSetVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerSetVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerIncVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerIncVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerDecVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerDecVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerSetPitch
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerSetPitch
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerIncPitch
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerIncPitch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QAudio
 * Method:    playerDecPitch
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QAudio_playerDecPitch
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
