/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qvoice_init.h"
/* Header for class com_qdreamer_qvoice_QEngine */

#ifndef _Included_com_qdreamer_qvoice_QEngine
#define _Included_com_qdreamer_qvoice_QEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    newEngine
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_qvoice_QEngine_newEngine
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    startEngine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_startEngine
  (JNIEnv *, jobject, jlong);

//提取声纹向量，请输入单通道音频
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QEngine_extractVector
  (JNIEnv *env, jobject obj, jlong jengine, jbyteArray jdata, jint jbytes, jint jis_end);
//向量比较
JNIEXPORT jfloat JNICALL Java_com_qdreamer_qvoice_QEngine_vectorCompare
  (JNIEnv *env, jobject obj, jlong jengine, jbyteArray jdata1, jbyteArray jdata2);

#ifdef USE_ASR
//设置语法识别命令词
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_updateCmds
  (JNIEnv *env, jobject obj, jlong jengine, jstring jparams);
#endif

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    feedEngine
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_feedEngine
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    cancelEngine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_cancelEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    setEngine
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_setEngine
  (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_setParamsEngine
  (JNIEnv *, jobject, jlong, jint, jfloat);
/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    resetEngine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_resetEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    deleteEngine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QEngine_deleteEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    readEngine
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QEngine_readEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    getFnEngine
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QEngine_getFnEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    getProbEngine
 * Signature: (J)[B
 */
JNIEXPORT jfloat JNICALL Java_com_qdreamer_qvoice_QEngine_getProbEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QEngine
 * Method:    getResultEngine
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QEngine_getResultEngine
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
