/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qvoice_init.h"
/* Header for class com_qdreamer_qvoice_QModule */

#ifndef _Included_com_qdreamer_qvoice_QModule
#define _Included_com_qdreamer_qvoice_QModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleNew
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_qvoice_QModule_moduleNew
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleDel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_qvoice_QModule_moduleDel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QModule_moduleStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleStop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QModule_moduleStop
  (JNIEnv *, jobject, jlong);


/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleFeed
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QModule_moduleFeed
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleSet
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_QModule_moduleSet
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qdreamer_qvoice_QModule
 * Method:    moduleRead
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QModule_moduleRead
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
