/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qvoice_init.h"
/* Header for class com_qdreamer_qvoice_OggHelper */

#ifndef _Included_com_qdreamer_qvoice_OggHelper
#define _Included_com_qdreamer_qvoice_OggHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_qvoice_OggHelper
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_qvoice_OggHelper_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qdreamer_qvoice_OggHelper
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_OggHelper_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_OggHelper
 * Method:    read
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_OggHelper_read
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_OggHelper
 * Method:    feed
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_OggHelper_feed
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_qdreamer_qvoice_OggHelper
 * Method:    stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_OggHelper_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_qvoice_OggHelper
 * Method:    delete
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_qvoice_OggHelper_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif