/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qvoice_init.h"
/* Header for class com_qdreamer_qvoice_QSession */

#ifndef _Included_com_qdreamer_qvoice_QSession
#define _Included_com_qdreamer_qvoice_QSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_qvoice_QSession
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_qvoice_QSession_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qdreamer_qvoice_QSession
 * Method:    sessionRead
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_qvoice_QSession_sessionRead
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_qvoice_QSession
 * Method:    exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_qvoice_QSession_exit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
