/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qvoice_init.h"
/* Header for class com_qdreamer_vprintWake_vprintWakeHelper */

#ifndef _Included_com_qdreamer_vprintWake_vprintWakeHelper
#define _Included_com_qdreamer_vprintWake_vprintWakeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    delete
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_delete
  (JNIEnv *, jobject , jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    read
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_read
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollSetFn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollSetFn
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollSetName
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollSetName
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollFeed
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollFeed
(JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollReset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollReset
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollEnd
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollEnd
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollClean
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollClean
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    enrollGetFn
 * Signature: (J)I
 */
JNIEXPORT jstring JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_enrollGetFn
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    recognitionStart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_recognitionStart
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:	  recognitionFeed
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_erecognitionFeed
(JNIEnv *env, jobject obj , jlong jvw, jbyteArray jdata, jint jbytes);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    recognitionReset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_recognitionReset
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    recognitionSetConf
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_recognitionSetConf
(JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_qdreamer_vprintWake_vprintWakeHelper
 * Method:    recognitionGetProb
 * Signature: (J)I
 */
JNIEXPORT jfloat JNICALL Java_com_qdreamer_vprintWake_vprintWakeHelper_recognitionGetProb
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
};
#endif
#endif
