/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qdreamer_image_Parse */

#ifndef _Included_com_qdreamer_image_Parse
#define _Included_com_qdreamer_image_Parse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qdreamer_image_Parse
 * Method:    readVec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_image_Parse_readVec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qdreamer_image_Parse
 * Method:    showVec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_image_Parse_showVec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_image_Parse
 * Method:    newParse
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_image_Parse_newParse
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_qdreamer_image_Parse
 * Method:    deleteParse
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_image_Parse_deleteParse
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qdreamer_image_Parse
 * Method:    processParse
 * Signature: (JLjava/lang/String;[C)[C
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_image_Parse_processParse
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
