/* DO NOT EDIT THIS FILE - it is machine generated */
#include "qtk/serde/qtk_serde_msgpack.h"
#include "wtk/asr/vad/wtk_vad2.h"
#include <jni.h>

/* Header for class com_qdreamer_vad_Vad */

#ifndef _Included_com_qdreamer_vad_Vad
#define _Included_com_qdreamer_vad_Vad
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    wtk_main_cfg_t *main_cfg;
    wtk_vad2_t *vad;
    wtk_strbuf_t *buf;
} mod_t;

static void on_vad_(mod_t *m, wtk_vad2_cmd_t cmd, short *data, int len) {
    int payload_pos;
    uint32_t payload_len;
    wtk_strbuf_t *buf = m->buf;
#define PACK_MSG(body)                                                         \
    do {                                                                       \
        wtk_strbuf_push(m->buf, NULL, sizeof(uint32_t));                       \
        payload_pos = m->buf->pos;                                             \
        {body} payload_len = m->buf->pos - payload_pos;                        \
        memcpy(m->buf->data + payload_pos - sizeof(payload_len), &payload_len, \
               sizeof(payload_len));                                           \
    } while (0)

    switch (cmd) {
    case WTK_VAD2_START:
        PACK_MSG(
            qtk_serde_msgpack_pack_map(1, buf, (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("type", buf,
                                     (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("start", buf,
                                     (qtk_io_writer)wtk_strbuf_push););
        break;
    case WTK_VAD2_DATA:
        PACK_MSG(
            qtk_serde_msgpack_pack_map(2, buf, (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("type", buf,
                                     (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("data", buf,
                                     (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("data", buf,
                                     (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_bin(data, len * 2, buf,
                                       (qtk_io_writer)wtk_strbuf_push););
        break;
    case WTK_VAD2_END:
        PACK_MSG(
            qtk_serde_msgpack_pack_map(1, buf, (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("type", buf,
                                     (qtk_io_writer)wtk_strbuf_push);
            qtk_serde_msgpack_pack_s("end", buf,
                                     (qtk_io_writer)wtk_strbuf_push););
        break;
    case WTK_VAD2_CANCEL:
        break;
    }

#undef PACK_MSG
}

/*
 * Class:     com_qdreamer_vad_Vad
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_vad_Vad_create(JNIEnv *env,
                                                         jobject ths,
                                                         jstring cfg) {
    mod_t *m = wtk_malloc(sizeof(mod_t));
    char *cfg_fn = (char *)(*env)->GetStringUTFChars(env, cfg, NULL);
    m->main_cfg = wtk_main_cfg_new_type(wtk_vad_cfg, cfg_fn);
    m->vad = wtk_vad2_new((wtk_vad_cfg_t *)m->main_cfg->cfg);
    m->buf = wtk_strbuf_new(1024, 1);
    wtk_vad2_set_notify(m->vad, m, (wtk_vad2_notify_f)on_vad_);
    return (jlong)m;
}

/*
 * Class:     com_qdreamer_vad_Vad
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_vad_Vad_destroy(JNIEnv *env,
                                                         jobject ths,
                                                         jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    wtk_vad2_delete(m->vad);
    wtk_main_cfg_delete(m->main_cfg);
    wtk_strbuf_delete(m->buf);
    wtk_free(m);
}

/*
 * Class:     com_qdreamer_vad_Vad
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_vad_Vad_start(JNIEnv *env, jobject ths,
                                                       jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    wtk_vad2_start(m->vad);
}

/*
 * Class:     com_qdreamer_vad_Vad
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_vad_Vad_reset(JNIEnv *env, jobject ths,
                                                       jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    wtk_vad2_reset(m->vad);
}

/*
 * Class:     com_qdreamer_vad_Vad
 * Method:    feed
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qdreamer_vad_Vad_feed(
    JNIEnv *env, jobject ths, jlong mod_ptr, jbyteArray audio, jint len) {
    jbyteArray result = NULL;
    mod_t *m = (mod_t *)mod_ptr;
    char *data = (char *)(*env)->GetByteArrayElements(env, audio, 0);
    wtk_vad2_feed(m->vad, data, len, 0);
    result = (*env)->NewByteArray(env, m->buf->pos);
    (*env)->SetByteArrayRegion(env, result, 0, m->buf->pos,
                               (jbyte *)m->buf->data);
    wtk_strbuf_reset(m->buf);
    return result;
}

/*
 * Class:     com_qdreamer_vad_Vad
 * Method:    feed_end
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_qdreamer_vad_Vad_feed_1end(JNIEnv *env, jobject ths, jlong mod_ptr) {
    jbyteArray result = NULL;
    mod_t *m = (mod_t *)mod_ptr;
    wtk_vad2_feed(m->vad, NULL, 0, 1);
    result = (*env)->NewByteArray(env, m->buf->pos);
    (*env)->SetByteArrayRegion(env, result, 0, m->buf->pos,
                               (jbyte *)m->buf->data);
    wtk_strbuf_reset(m->buf);
    return result;
}

#ifdef __cplusplus
}
#endif
#endif
