/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qdreamer_asr_Asr */

#ifndef _Included_com_qdreamer_asr_Asr
#define _Included_com_qdreamer_asr_Asr
#ifdef __cplusplus
extern "C" {
#endif

#include "wtk/asr/wfst/qtk_asr_wrapper.h"

typedef struct {
    wtk_main_cfg_t *mcfg;
    qtk_asr_wrapper_t *impl;
} mod_t;
/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_qdreamer_asr_Asr_create(JNIEnv *env,
                                                         jobject ths,
                                                         jstring cfg) {
    mod_t *m = wtk_malloc(sizeof(mod_t));
    char *cfg_fn = (char *)(*env)->GetStringUTFChars(env, cfg, NULL);
    m->mcfg = qtk_asr_wrapper_cfg_new(cfg_fn);
    m->impl = qtk_asr_wrapper_new(m->mcfg->cfg);
    return (jlong)m;
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_asr_Asr_destroy(JNIEnv *env,
                                                         jobject ths,
                                                         jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    qtk_asr_wrapper_delete(m->impl);
    qtk_asr_wrapper_cfg_delete(m->mcfg);
    wtk_free(m);
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_asr_Asr_start(JNIEnv *env, jobject ths,
                                                       jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    wtk_string_t v = wtk_string("use_hint=1;");
    qtk_asr_wrapper_start2(m->impl, v.data, v.len);
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_asr_Asr_reset(JNIEnv *env, jobject ths,
                                                       jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    qtk_asr_wrapper_reset(m->impl);
}

static jstring str_to_jni(JNIEnv *env, wtk_string_t *v) {
    char buf[8192] = {0};
    jstring result;
    if (v->len > sizeof(buf) - 1) {
        wtk_string_t *v0 = wtk_string_dup_data_pad0(v->data, v->len);
        result = (*env)->NewStringUTF(env, v0->data);
        wtk_string_delete(v0);
    } else {
        memcpy(buf, v->data, v->len);
        result = (*env)->NewStringUTF(env, buf);
    }
    return result;
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    get_result
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qdreamer_asr_Asr_get_1result(JNIEnv *env,
                                                                jobject ths,
                                                                jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    wtk_string_t v;
    qtk_asr_wrapper_get_result(m->impl, &v);
    return str_to_jni(env, &v);
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    get_hint_result
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qdreamer_asr_Asr_get_1hint_1result(
    JNIEnv *env, jobject ths, jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    wtk_string_t v;
    qtk_asr_wrapper_get_hint_result(m->impl, &v);
    return str_to_jni(env, &v);
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    feed
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_asr_Asr_feed(JNIEnv *env, jobject ths,
                                                      jlong mod_ptr,
                                                      jbyteArray audio,
                                                      jint len) {
    mod_t *m = (mod_t *)mod_ptr;
    char *data = (char *)(*env)->GetByteArrayElements(env, audio, 0);
    qtk_asr_wrapper_feed(m->impl, data, len, 0);
}

/*
 * Class:     com_qdreamer_asr_Asr
 * Method:    feed_end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qdreamer_asr_Asr_feed_1end(JNIEnv *env,
                                                           jobject ths,
                                                           jlong mod_ptr) {
    mod_t *m = (mod_t *)mod_ptr;
    qtk_asr_wrapper_feed(m->impl, NULL, 0, 1);
}

#ifdef __cplusplus
}
#endif
#endif
