#ifndef __QTK_STITCH_DEF_H__
#define __QTK_STITCH_DEF_H__

#include "wtk/core/wtk_queue.h"

#ifdef __cplusplus
extern "C" {
#endif

//detector
#define QTK_STITCH_FEATURE_DETECTOR_ORB  0
#define QTK_STITCH_FEATURE_DETECTOR_SIFT 1
#define QTK_STITCH_FEATURE_DETECTOR_BRISK 2
#define QTK_STITCH_FEATURE_DETECTOR_AKAZE 3

//matcher
#define QTK_STITCH_FEATURE_MATCHER_HOMOGRAPHY 0
#define QTK_STITCH_FEATURE_MATCHER_AFFINE 1

//estimator
#define QTK_STITCH_CAMERA_ESTIMATOR_HOMOGRAPHY 0
#define QTK_STITCH_CAMERA_ESTIMATOR_AFFINE 1

//adjuster
#define QTK_STITCH_CAMERA_ADJUSTER_RAY 0
#define QTK_STITCH_CAMERA_ADJUSTER_REPROJ 1
#define QTK_STITCH_CAMERA_ADJUSTER_AFFINE 2
#define QTK_STITCH_CAMERA_ADJUSTER_NO 3

//wave correct
#define QTK_STITCH_WAVE_CORRECT_HORIZ 0
#define QTK_STITCH_WAVE_CORRECT_VERT 1
#define QTK_STITCH_WAVE_CORRECT_AUTO 2
#define QTK_STITCH_WAVE_CORRECT_NO 3

//warper
#define QTK_STITCH_WARPER_SPHERICAL 0
#define QTK_STITCH_WARPER_PLANE 1
#define QTK_STITCH_WARPER_AFFINE 2
#define QTK_STITCH_WARPER_CYLINDRICAL 3
#define QTK_STITCH_WARPER_FISHEYE 4
#define QTK_STITCH_WARPER_STEREOGRAPHIC 5
#define QTK_STITCH_WARPER_COMPRESSEDPLANEA2B1 6
#define QTK_STITCH_WARPER_COMPRESSEDPLANEA1_5B1 7
#define QTK_STITCH_WARPER_COMPRESSEDPLANEPORTRAITA2B1 8
#define QTK_STITCH_WARPER_COMPRESSEDPLANEPORTRAITA1_5B1 9
#define QTK_STITCH_WARPER_PANINIA2B1 10
#define QTK_STITCH_WARPER_PANINIA1_5B1 11
#define QTK_STITCH_WARPER_PANINIPORTRAITA2B1 12
#define QTK_STITCH_WARPER_PANINIPORTRAITA1_5B1 13
#define QTK_STITCH_WARPER_MERCATOR 14
#define QTK_STITCH_WARPER_TRANSVERSEMERCATOR 15

//Exposure Compensator
#define QTK_STITCH_EXPOSURE_GAIN_BLOCK 0
#define QTK_STITCH_EXPOSURE_GAIN 1
#define QTK_STITCH_EXPOSURE_CHANNEL 2
#define QTK_STITCH_EXPOSURE_CHANNEL_BLOCKS 3
#define QTK_STITCH_EXPOSURE_NO 4

//seam finder
#define QTK_STITCH_FINDER_DP_COLOR 0
#define QTK_STITCH_FINDER_DP_COLORGRAD 1
#define QTK_STITCH_FINDER_GC_COLOR 2
#define QTK_STITCH_FINDER_GC_COLORGRAD 3
#define QTK_STITCH_FINDER_VORONOI 4
#define QTK_STITCH_FINDER_NO 5

//blender
#define QTK_STITCH_BLENDER_MULTIBAND 0
#define QTK_STITCH_BLENDER_FEATHER 1
#define QTK_STITCH_BLENDER_NO 2

//timelapse
#define QTK_STITCH_TIMELAPSE_NO 0
#define QTK_STITCH_TIMELAPSE_AS_IS 1
#define QTK_STITCH_TIMELAPSE_CROP 2


//use img type 
#define QTK_STITCH_USE_IMG_RGB 0
#define QTK_STITCH_USE_IMG_NV12 1

//fix point
#define QTK_STITCH_FIX_POINT 10

typedef struct qtk_stitch_queue_data{
    wtk_queue_node_t node;
    int type;
    int num;
    void *img_data; //qtk_stitch_image_t
    void *feature_data;
}qtk_stitch_queue_data_t;

#ifdef __cplusplus
}
#endif

#endif