/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[75] = 
{
    "epsilon",
    "eh0",
    "aa0",
    "ey0",
    "ey1",
    "ih1",
    "aw1",
    "ao1",
    "ao0",
    "aw0",
    "ow0",
    "ah0",
    "aa1",
    "ae1",
    "er0",
    "eh1",
    "ae0",
    "ow1",
    "ih0",
    "ay0",
    "w-ah0",
    "ah1",
    "w-ey1",
    "ay1",
    "b",
    "ch",
    "s",
    "k",
    "t-s",
    "sh",
    "d",
    "t",
    "jh",
    "iy0",
    "iy1",
    "uw1",
    "uw0",
    "oy1",
    "y-uw0",
    "y-uw1",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "m",
    "m-ae1",
    "m-ae0",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "er1",
    "p",
    "r",
    "z",
    "th",
    "dh",
    "y-uh1",
    "y-er1",
    "y-uh0",
    "y-er0",
    "y-ah0",
    "ah0-w",
    "ah1-w",
    "v",
    "g-zh",
    "k-s",
    "g-z",
    "k-sh",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    6255, /* b */
    6397, /* c */
    7075, /* d */
    7199, /* e */
    13152, /* f */
    13163, /* g */
    13706, /* h */
    13968, /* i */
    18116, /* j */
    18256, /* k */
    18266, /* l */
    18404, /* m */
    18594, /* n */
    18948, /* o */
    23226, /* p */
    23261, /* q */
    23262, /* r */
    25064, /* s */
    26196, /* t */
    26531, /* u */
    28722, /* v */
    28735, /* w */
    28922, /* x */
    28984, /* y */
    29549, /* z */
    0
};

